spring.application.name:
  authorization-service

server:
  port:  8088

  # config jwt
  jwt:
    #    base64-secret: ${base64-secret:mRD5Fnrts6GBZRjpQ+95KbJVwllB1qGbfjK55iCV9qAD2wIZ+AGMQKw7BNldcSVOscnyoLaRY0mJ2i0950PtIg==}
    base64-secret: ${base64-secret:TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==}
    token-validity-in-seconds: ${token-validity-in-seconds:30000}

application:
  security:
    rsa:
      rsa-public-key: classpath:certs/public-key.pem
      rsa-private-key: classpath:certs/private-key.pem
    jwt:
      access-token-validity-in-seconds: 300 # 5 minutes
      refresh-token-validity-in-seconds: 604800 #7 days